const {createClient}=supabase;
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/notify-new-request`;
const PRIVACY_VERSION='1.0';
const DURATION_HOURS={'Außenreinigung':2,'Innenraumreinigung':4,'Polsterreinigung':4,'Komplettaufbereitung':8,'Politur':8,'Lackversiegelung':8};
function calculateDuration(){const service=$('service_type').value;if(service!=='Fahrzeugpflege')return{hours:2,label:'2 Stunden'};const options=[...document.querySelectorAll('input[name=care]:checked')].map(x=>x.value);let hours=options.reduce((s,x)=>s+(DURATION_HOURS[x]||0),0);if(!hours)hours=2;const days=Math.floor(hours/8),rest=hours%8;let label;if(rest===0)label=`${days} Arbeitstag${days===1?'':'e'}`;else if(hours===4)label='½ Arbeitstag';else label=`${hours} Stunden`;return{hours,label}}
function ensureDurationBox(){const care=$('care');if(!care)return;let el=$('durationInfo');if(!el){el=document.createElement('div');el.id='durationInfo';el.className='notice duration';care.insertAdjacentElement('afterend',el)}const d=calculateDuration();el.innerHTML=`<b>Voraussichtliche Bearbeitungsdauer: ${d.label}</b><br>Der Termin wird erst nach Prüfung und Bestätigung verbindlich.`}
async function loadBookedWindows(){const from=new Date();from.setDate(from.getDate()+1);const to=new Date(from);to.setDate(to.getDate()+90);const{data,error}=await db.rpc('get_all_booked_windows',{p_from:from.toISOString().slice(0,10),p_to:to.toISOString().slice(0,10)});if(error){console.warn('Verfügbarkeit:',error.message);return[]}return data||[]}
function addBusinessDays(date,count){const d=new Date(date);while(count>0){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)count--}return d}
function makeDesiredBlocks(date,time,duration){const blocks=[],base=new Date(`${date}T08:00:00`);if(duration.hours>=8){let remaining=duration.hours,day=new Date(base);while(remaining>=8){while(day.getDay()===0||day.getDay()===6)day.setDate(day.getDate()+1);const start=new Date(day);start.setHours(8,0,0,0);const end=new Date(day);end.setHours(16,0,0,0);blocks.push([start,end]);remaining-=8;day=addBusinessDays(day,1)}if(remaining>0){while(day.getDay()===0||day.getDay()===6)day.setDate(day.getDate()+1);const start=new Date(day);start.setHours(8,0,0,0);blocks.push([start,new Date(start.getTime()+remaining*3600000)])}}else if(duration.hours===4){const start=new Date(base);if(time==='13:00 – 15:00'||time==='15:00 – 17:00')start.setHours(13,0,0,0);blocks.push([start,new Date(start.getTime()+14400000)])}else{const start=new Date(base);if(time.startsWith('10:00'))start.setHours(10);else if(time.startsWith('13:00'))start.setHours(13);else if(time.startsWith('15:00'))start.setHours(15);blocks.push([start,new Date(start.getTime()+duration.hours*3600000)])}return blocks}
function overlaps(date,time,windows,duration){return makeDesiredBlocks(date,time,duration).some(([s,e])=>windows.some(w=>new Date(w.booking_start)<e&&new Date(w.booking_end)>s))}
async function validateAvailability(){const date=$('requested_date').value;if(!date)return true;const windows=await loadBookedWindows();if(overlaps(date,$('requested_time').value,windows,calculateDuration())){$('msg').textContent='Der gewünschte Zeitraum ist bereits belegt. Bitte wählen Sie einen anderen Termin.';$('msg').classList.remove('hidden');return false}return true}
function pick(s){$('service_type').value=s;$('title').textContent=s;$('box').classList.remove('hidden');$('care').classList.toggle('hidden',s!=='Fahrzeugpflege');$('parts').classList.toggle('hidden',s==='Fahrzeugpflege');ensureDurationBox();window.scrollTo({top:$('box').offsetTop-20,behavior:'smooth'})}
function closeForm(){$('box').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}
window.pick=pick;window.closeForm=closeForm;
function initApp(){const tomorrow=new Date(Date.now()+86400000);$('requested_date').min=tomorrow.toISOString().slice(0,10);document.querySelectorAll('input[name=care]').forEach(x=>x.addEventListener('change',ensureDurationBox));$('requested_time').addEventListener('change',ensureDurationBox);$('requested_date').addEventListener('change',validateAvailability);ensureDurationBox();$('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;if(!$('privacy_consent').checked){$('msg').textContent='Bitte bestätigen Sie zuerst die Datenschutzerklärung.';$('msg').classList.remove('hidden');return}b.disabled=true;b.textContent='Wird gesendet …';const requestId=crypto.randomUUID(),duration=calculateDuration();try{if(!(await validateAvailability()))return;const d={id:requestId,service_type:$('service_type').value,status:'Neue Anfrage',first_name:$('first_name').value,last_name:$('last_name').value,phone:$('phone').value,email:$('email').value,vehicle_type:$('vehicle_type').value,make:$('make').value,model:$('model').value,color:$('color').value,year:$('year').value?Number($('year').value):null,plate:$('plate').value,care_options:[...document.querySelectorAll('input[name=care]:checked')].map(x=>x.value),dirt_level:$('dirt_level').value,pet_hair:$('pet_hair').value,details:$('details').value,quantity:Number($('quantity').value)||null,tire_type:$('tire_type').value,requested_date:$('requested_date').value,requested_time:$('requested_time').value,message:$('message').value,privacy_consent:true,duration_hours:duration.hours,duration_label:duration.label};const r=await db.from('requests').insert(d);if(r.error)throw r.error;for(const file of [...($('photos')?.files||[])]){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const safe=/^[a-z0-9]+$/.test(ext)?ext:'jpg';const path=`${requestId}/${crypto.randomUUID()}.${safe}`;const up=await db.storage.from('vehicle-photos').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error)throw up.error;const pr=await db.from('request_photos').insert({request_id:requestId,storage_path:path});if(pr.error)throw pr.error}const notify=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:d})});if(!notify.ok)console.warn('Benachrichtigung:',await notify.text());$('msg').textContent=`Vielen Dank. Ihre Anfrage wurde erfolgreich übermittelt. Voraussichtliche Bearbeitungsdauer: ${duration.label}. Der Termin wird nach Prüfung durch T.S. Serviceleistungen bestätigt.`;$('msg').classList.remove('hidden');e.target.reset();ensureDurationBox()}catch(err){$('msg').textContent='Die Anfrage konnte nicht gesendet werden: '+err.message;$('msg').classList.remove('hidden')}finally{b.disabled=false;b.textContent='Anfrage absenden'}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initApp);else initApp();
