const {createClient}=supabase;
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/notify-new-request`;
const DURATION_HOURS={'Außenreinigung':2,'Innenraumreinigung':4,'Polsterreinigung':4,'Komplettaufbereitung':8,'Politur':8,'Lackversiegelung':8};
function calculateDuration(){const service=$('service_type').value;if(service!=='Fahrzeugpflege')return{hours:2,label:'2 Stunden'};const options=[...document.querySelectorAll('input[name=care]:checked')].map(x=>x.value);let hours=options.reduce((s,x)=>s+(DURATION_HOURS[x]||0),0);if(!hours)hours=2;return{hours,label:hours===4?'½ Arbeitstag':hours===8?'1 Arbeitstag':`${hours} Stunden`}}
function ensureDurationBox(){const el=$('durationInfo');if(!el)return;const d=calculateDuration();el.innerHTML=`<b>Voraussichtliche Bearbeitungsdauer: ${d.label}</b><br>Der Termin wird erst nach Prüfung und Bestätigung durch T.S. Serviceleistungen verbindlich.`}
function pick(service){$('service_type').value=service;$('title').textContent=service;$('box').classList.remove('hidden');$('serviceHint').textContent=service==='Gartenarbeiten'?'Bitte beschreiben Sie die Arbeiten sowie Schnitt- und Grünreste, die gegebenenfalls abtransportiert werden sollen.':service==='Foto & Drohnenfotografie'?'Bitte nennen Sie Objekt, Einsatzort und gewünschte Aufnahmen (Foto, Video oder beides).':'Bitte tragen Sie die gewünschten Angaben ein.';$('vehicleBlock').classList.toggle('hidden',!['Fahrzeugpflege','Ersatzteilanfrage','Reifenanfrage','Zubehörmontage'].includes(service));$('care').classList.toggle('hidden',service!=='Fahrzeugpflege');$('parts').classList.toggle('hidden',service==='Fahrzeugpflege');ensureDurationBox();window.scrollTo({top:$('box').offsetTop-20,behavior:'smooth'})}
function resetService(){$('box').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function loadBookedWindows(){const from=new Date();from.setDate(from.getDate()+1);const to=new Date(from);to.setDate(to.getDate()+90);const {data,error}=await db.rpc('get_all_booked_windows',{p_from:from.toISOString().slice(0,10),p_to:to.toISOString().slice(0,10)});if(error){console.warn(error.message);return[]}return data||[]}
function overlaps(date,time,windows,duration){const startHour=time.startsWith('13')?13:time.startsWith('15')?15:time.startsWith('10')?10:8;const start=new Date(`${date}T${String(startHour).padStart(2,'0')}:00:00`);const end=new Date(start.getTime()+duration.hours*3600000);return windows.some(w=>new Date(w.booking_start)<end&&new Date(w.booking_end)>start)}
async function validateAvailability(){const date=$('requested_date').value;if(!date)return true;const duration=calculateDuration();const windows=await loadBookedWindows();if(overlaps(date,$('requested_time').value,windows,duration)){$('msg').textContent='Der gewünschte Zeitraum ist bereits belegt. Bitte wählen Sie einen anderen Termin.';$('msg').classList.remove('hidden');return false}return true}
function init(){const tomorrow=new Date(Date.now()+86400000);$('requested_date').min=tomorrow.toISOString().slice(0,10);document.querySelectorAll('input[name=care]').forEach(x=>x.addEventListener('change',ensureDurationBox));$('requested_time').addEventListener('change',ensureDurationBox);$('requested_date').addEventListener('change',validateAvailability);ensureDurationBox();$('form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Wird gesendet …';const duration=calculateDuration();const requestId=crypto.randomUUID();try{if(!(await validateAvailability()))return;const d={id:requestId,service_type:$('service_type').value,status:'Neue Anfrage',first_name:$('first_name').value,last_name:$('last_name').value,phone:$('phone').value,email:$('email').value,vehicle_type:$('vehicle_type').value,make:$('make').value,model:$('model').value,color:$('color').value,year:$('year').value?Number($('year').value):null,plate:$('plate').value,care_options:[...document.querySelectorAll('input[name=care]:checked')].map(x=>x.value),dirt_level:$('dirt_level').value,pet_hair:$('pet_hair').value,details:$('details').value,quantity:Number($('quantity').value)||null,tire_type:$('tire_type').value,requested_date:$('requested_date').value,requested_time:$('requested_time').value,message:$('message').value,privacy_consent:$('privacy_consent').checked,duration_hours:duration.hours,duration_label:duration.label};const r=await db.from('requests').insert(d);if(r.error)throw r.error;for(const file of [...($('photos').files||[])]){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${requestId}/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('vehicle-photos').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error)throw up.error;const pr=await db.from('request_photos').insert({request_id:requestId,storage_path:path});if(pr.error)throw pr.error}const notify=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:d})});if(!notify.ok)console.warn(await notify.text());$('msg').textContent=`Vielen Dank. Ihre Anfrage wurde erfolgreich übermittelt. Voraussichtliche Bearbeitungsdauer: ${duration.label}. Der Termin wird nach Prüfung bestätigt.`;$('msg').classList.remove('hidden');e.target.reset();$('box').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}catch(err){$('msg').textContent='Die Anfrage konnte nicht gesendet werden: '+err.message;$('msg').classList.remove('hidden')}finally{b.disabled=false;b.textContent='Anfrage absenden'}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
